// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/32f0a90dab26f70b206407ac24d4d622d0f0f408/cookie-parser/cookie-parser.d.ts
declare module "cookie-parser" {
    import express = require('express');
    function e(secret?: string, options?: any): express.RequestHandler;
    export = e;
}
